### ISSUE TITLE
about the Navigation & Planning part

### ISSUE THREAD

**Issue by QingXinHu123** [takeitallsource/awesome-autonomous-vechicles#15]
First of all，thanks for your contribution！And dose there has something about Decision Making for Navigation & Planning part in the lists of Papers？

**Comment by manfreddiaz** [comment]
Hi @QingXinHu123, I haven't been updating the repo lately. If your looking for decision making in the context on AD it is mostly like happening in the navigation and planning parts of the pipeline. You can take a look, for instance, to https://arxiv.org/abs/1604.07316 and search for all the papers that make a reference to this one. This will give you a gist of what has been done recently in decision making for AD.
